let enemies = [
  'Player',
  'Giant Bat',
  'Cyclops',
  'Wyvern',
  'Green Dragon',
  'Blue Dragon',
  'Red Dragon',
  'Gargoyle',
  'Goblin Scout',
  'Goblin Spearman',
  'Goblin Rider',
  'Gorgon',
  'Impling',
  'Imp',
  'Winged Imp',
  'Lizard Spearman',
  'Lizard Guard',
  'Minotaur',
  'Minotaur Knight',
  'Minotaur Beast',
  'Red Oni',
  'Orc',
  'Orc Wizard',
  'Orc Rider',
  'Shade',
  'Shadow Spirit',
  'Grisly Shadow',
  'Skeleton',
  'Skeleton Spearman',
  'Skeleton Warrior',
  'Mucus',
  'Green Slime',
  'Gray Spider',
  'Turquoise Spider',
  'Purple Widow',
  'Troll',
  'Wild Wolf',
  'Werewolf',
  'Hooded Werewolf',
  'Brainless',
  'Momba',
  'Rogue Momba',
  'Bow Momba',
  'Shield Momba',
  'Fire Momba',
  'Ice Momba',
  'Vortex Momba',
  'Black Momba',
  'Forest Momba',
  'Ghost Momba',
  'Shadow Momba',
  'Divinity Momba',
];

exports.EnemyPages = enemies;
